apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "context" $ ) | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  serviceName: {{ include "wishlsits.v1.api.svc.headless" . }}
  {{- $podLabels := .Values.podLabels }}
  selector:
    matchLabels:
      app: unmango-wishlists
  template:
    metadata:
      labels:
        app: unmango-wishlists
    spec:
      containers:
        - name: api
          image: {{ include "wishlists.v1.api.image" . }}
          ports:
            - name: http
              containerPort: 5080
          env:
            - name: PUID
              value: {{ .Values.global.uid | quote }}
            - name: PGID
              value: {{ .Values.global.gid | quote }}
